site_name: VLM Cookbook
site_url: https://autonomi-ai.github.io/vlm-cookbook
site_author: Sudeep Pillai
site_dir: site
site_description: >-
  Tools and cookbook recipes for working with VLMs (Vision-Language Models).
repo_url: https://github.com/autonomi-ai/vlm-cookbook
repo_name: autonomi-ai/vlm-cookbook
docs_dir: docs
use_directory_urls: false
copyright: >
  Copyright &copy; 2022 - 2024 <a href="https://autonomi.ai" target="_blank">Autonomi AI, Inc.</a> All rights reserved.

nav:
  - 🧑‍🍳 Cookbook: index.md

plugins:
- include-markdown
- autorefs
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        paths: [.]
        options:
          annotations_path: brief
          members_order: source
          line_length: 80
          docstring_options:
            ignore_init_summary: false
          merge_init_into_class: false
          docstring_style: google
          docstring_section_style: list
          show_docstring_description: true
          show_source: true
          show_root_heading: yes
          show_bases: false
          show_signature_annotations: true
          separate_signature: true
          signature_crossrefs: true
- tags
- search
- table-reader
- exclude:
    glob:
      - build/*
    regex:
      - '.*\.(tmp|bin|tar)$'

markdown_extensions:
- attr_list
- md_in_html
- admonition
- pymdownx.betterem
- pymdownx.details
- pymdownx.superfences
- markdown.extensions.footnotes
- markdown.extensions.attr_list
- markdown.extensions.def_list
- markdown.extensions.tables
- markdown.extensions.abbr
- markdown.extensions.md_in_html
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.extra
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- toc:
    permalink: True
    toc_depth: 4

theme:
  # favicon:
  # logo: :cook:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.instant.progress
    - toc.follow

extra:
  analytics:
    provider: google
    property: G-J38LQZWLM3
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:support@autonomi.ai
    - icon: fontawesome/brands/github
      link: https://github.com/autonomi-ai/vlm-cookbook
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/74939899
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/autonomi_ai
    - icon: fontawesome/brands/discord
      link: https://discord.gg/a6suHC9B5E
